name: Build MTConnect C++ Agent

on:
  # Enable automated build once verified
  pull_request:
    paths-ignore: ["**/*.md", "LICENSE.txt", ".gitignore"]
    branches: [ "main", "main-dev" ]

  push:
    paths-ignore: ["**/*.md", "LICENSE.txt", ".gitignore"]
    branches: [ "main", "main-dev" ]
    tags:
      - "v*.*.*"

  # Allow manually run workflows
  workflow_dispatch:

jobs:
  build_windows:
    runs-on: windows-2019
    strategy:
      matrix:
        arch: ["x86"]
        include:
          - arch: "x86"
            profile: "vs32"

    steps:
    - name: Checkout Agent
      uses: actions/checkout@v3

    - name: Cache conan packages
      id: cache-npm
      uses: actions/cache@v3
      env:
       cache-name: cache-conan-packages
      with:
        path: ~/.conan2
        key: ${{ runner.os }}-build-${{ matrix.arch }}-${{ hashFiles('**/conanfile.py') }}

    - name: Install Conan
      uses: turtlebrowser/get-conan@v1.2

    - name: Initialize VS Dev Env
      uses: seanmiddleditch/gha-setup-vsdevenv@master
      with:
        arch: ${{ matrix.arch }}
        host_arch: ${{ matrix.arch }}
          
    - name: Build and Test C++ Agent
      run: |
        conan profile detect -f
        conan create . --build=missing -pr conan/profiles/${{ matrix.profile }} -o with_docs=False -o cpack=True -o zip_destination=C:\Users\runneradmin\

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          C:/Users/runneradmin/agent*.zip
        token: ${{ secrets.RELEASE_GITHUB_TOKEN }}

        
